// resources/ts/Layouts/App.tsx
import type { ReactNode } from 'react';
import Header from '../Components/Header';
import Body from '../Components/Body';
import Footer from '../Components/Footer';

interface AppLayoutProps {
    children?: ReactNode;
    currentRoute?: string;
}

export default function App({ children, currentRoute = 'home' }: AppLayoutProps) {
    return (
        <div className="flex min-h-screen flex-col">
            <Header currentRoute={currentRoute} />
            <main className="flex-1">
                <Body>{children}</Body>
            </main>
            <Footer />
        </div>
    );
}

// resources/ts/App.vue
<template>
  <div id="flex flex-col min-h-screen">
    <!-- Menggunakan komponen yang telah diimpor -->
    <Header />
    
    <main class="flex-1">
      <Body />
    </main>
    
    <Footer />
  </div>
</template>

<script setup lang="ts">
// Mengimpor komponen dengan TypeScript
import Header from './Components/Header.vue';
import Body from './Components/Body.vue';
import Footer from './Components/Footer.vue';
</script>
