// resources/js/Components/GuestNavLink.vue
<script setup lang='ts'>
import { route } from 'ziggy-js'
import { Ziggy } from './ziggy.js'

route('home', undefined, undefined, Ziggy);

  const app = Vue.createApp({
   data() {
    return {
yayasans: [
        {name: 'Sejarah Yayasan', url:( 'posts.show', 1)},
        {name: 'AD/ART Yayasan', url: ( 'posts.show', 2)},
        {name: 'Pengurus Yayasan', url: 'pengurus_yayasan.index'},
{name: 'Fasilitas Yayasan', url: ('pengurus_yayasan.index', 3)},
{name: 'Kontak Yayasan', url: ('datayayasan.show', 1)}
],
tk: [
        {name: 'Sejarah TK', url:( 'posts.show', 1)},
        {name: 'AD/ART TK', url: ( 'posts.show', 2)},
        {name: 'Pengurus TK', url: 'pengurus_yayasan.index'},
{name: 'Fasilitas TK', url: ('pengurus_yayasan.index', 3)},
{name: 'Kontak TK', url: ('datayayasan.show', 1)}
],
sekolahmenengah: [
        {name: 'SMP', url: 'https://smpafbs.sch.id/'},
        {name: 'SMA', url: 'https://www.smaafbs.sch.id/'}
],
info: [
        {name: 'Pengumuman', url: 'fles.index'},
        {name: 'video', url: 'video.index'}
],
showDiv: true
}
}
});
app.mount('#guestnavlink');
</script>
   <template>
<nav id="guestnavlink" class="a354-bar a354-mobile a354-light-grey ">
<a :href="$route('home')" class="a354-bar-item a354-button">Home</a>
<div class="a354-dropdown-click" >
      <button class="a354-button" v-show="showDiv" v-for="x in yayasans">
    <a class="a354-bar-item w3-button" :href="$route(x.url)">{{ x.name }}</a>
 </button>
</div>
<div class="a354-dropdown-click" >
      <button class="a354-button" v-show="showDiv" v-for="x in tk">
    <a class="a354-bar-item a354-button" :href="$route(x.url)">{{ x.name }}</a>
 </button>
</div>
<div v-for="x in sekolahmenengah">
    <a class="a354-bar-item a354-button" :href="$route(x.url)">{{ x.name }}</a>
</div>
<div class="a354-dropdown-click" >
      <button class="a354-button" v-show="showDiv" v-for="x in info">
    <a class="a354-bar-item a354-button" :href="$route(x.url)">{{ x.name }}</a>
 </button>
</div>
</nav>
</template>

// resources/ts/Components/GuestNavLink.tsx
import Dropface, { mydropface } from '@/Components/SubComponents/DropFaces';
import { useRoute } from 'ziggy-js';
import { Ziggy } from './ziggy.js';
import { 
  MegaMenu,
  MegaMenuDropdownToggle,
  NavbarBrand,
  NavbarCollapse,
  NavbarLink,
  NavbarToggle
} from 'flowbite-react';
import { HiChevronDown } from 'react-icons/hi';
import React from 'react';
import LogIn from '@/Components/SubComponents/LogIn';

export function Guestnav() {
const route = useRoute(Ziggy);
const yayasans: mydropface[]=[
        {id: 1, link: "'posts.show', 1", title: 'Sejarah Yayasan'},
        {id: 2, link: "'posts.show', 2", title: 'AD/ART Yayasan'},
        {id: 3, link: "'pengurus_yayasan.index'", title: 'Pengurus Yayasan'},
{id: 4, link: "'posts.show', 3", title: 'Fasilitas Yayasan'},
{id: 5, link: "'datayayasan.show', 1", title: 'Kontak Yayasan'}
];
const tk: mydropface[]= [
        {link: "'posts.show', 4", title: 'Sejarah TK'},
        {link: "'posts.show', 5", title: 'AD/ART TK'},
        {link: "'pengurus_yayasan.index'", title: 'Pengurus TK'},
{link: "'posts.show', 6", title: 'Fasilitas TK'},
{link: "'datayayasan.show', 1", title: 'Kontak TK'}
];
const info: mydropface[]=[
        {link: "'fles.index'", title: 'Pengumuman'},
        {link: "'video.index'", title: 'video' }
];

return(
<>
<MegaMenu>
  <NavbarBrand href="/">
    <img alt="" src="/favicon.svg" 
    className="mr-3 h-6 
    sm:h-9" />
    <span className="self-center whitespace-nowrap 
    text-xl font-semibold dark:text-white">Yayasan Dar Al Furqon Al Hakim</span>
  </NavbarBrand>
  <div>
    <LogIn/>
  </div>
  <NavbarToggle />
  <NavbarCollapse>
    <NavbarLink link={ route('home') }>Beranda</NavbarLink>
    <MegaMenuDropdownToggle>
      Yayasan
      <HiChevronDown className="ml-2" />
    </MegaMenuDropdownToggle>
    <MegaMenuDropdownToggle>
      TK
      <HiChevronDown className="ml-2" />
    </MegaMenuDropdownToggle>
    <NavbarLink link="https://smpafbs.sch.id">SMP</NavbarLink>
    <NavbarLink link="https://smaafbs.sch.id">SMA</NavbarLink>
    <MegaMenuDropdownToggle>
      Info
      <HiChevronDown className="ml-2" />
    </MegaMenuDropdownToggle>
    </NavbarCollapse>  
<Dropface himpunan = {yayasans} />
<Dropface himpunan = {tk} />
<Dropface himpunan = {info} />
</MegaMenu>
</>
);
};
