// resources/js/Components/HeadSlot.vue
<script setup>
import { Head } from '@inertiajs/vue3'

defineProps({ title: String })
</script>

 <template>
 <Head>
<title><slot></slot></title>
<meta head-key="description" name="description" content="Website tentang Yayasan Dar Al Furqon Al Hakim" />
<link rel="icon" type="image/x-icon" href="favicon.ico">
</Head>
</template>

// resources/ts/Components/Headslot.tsx
import { Head } from '@inertiajs/react';

export default function mainhead(props): HTMLHeadElement {
  let mainhead:HTMLHeadElement =<Head>
<title>
{ props.title }<title>
<meta head-key="description" name="description" content="Website tentang Yayasan Dar Al Furqon Al Hakim" />
<link rel="icon" type="image/x-icon" href="favicon.ico">
</Head>;
return mainhead;
}
