// resources/ts/Components/NavbarGuest.vue
<template>
    <nav class="flex items-center space-x-6">
        <!-- Link Publik Biasa -->
        <Link :href="route('home')" 
            :class="[route().current('home') ? 'text-blue-600 font-bold' : 'text-gray-600 hover:text-blue-600']">
            Beranda
        </Link>

        <!-- Menu Dropdown (Contoh: Media/Video) -->
        <div class="relative group" ref="dropdownRef">
            <button 
                @click="isDropdownOpen = !isDropdownOpen"
                class="flex items-center space-x-1 text-gray-600 hover:text-blue-600 focus:outline-none"
                :class="{'text-blue-600 font-bold': route().current('video.*')}"
            >
                <span>Yayasan</span>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 transition-transform duration-200" :class="{'rotate-180': isDropdownOpen}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                </svg>
            </button>
 <!-- Dropdown Menu -->
            <Transition
                enter-active-class="transition ease-out duration-100"
                enter-from-class="transform opacity-0 scale-95"
                enter-to-class="transform opacity-100 scale-100"
                leave-active-class="transition ease-in duration-75"
                leave-from-class="transform opacity-100 scale-100"
                leave-to-class="transform opacity-0 scale-95"
            >
                <div v-if="isDropdownOpen" class="absolute left-0 mt-2 w-48 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 z-50">
                    <div class="py-1">
                        <Link :href="route('posts.show', 1)" class="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600">
                            Visi
                        </Link>
                        <Link :href="route('posts.show', 2)" class="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600">
                            Misi
                        </Link>
                        <Link :href="route('posts.show', 3)" class="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600">
                            Sejarah
                        </Link>
                        <Link :href="route('pengurus_yayasan.index')" class="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600">
                            👥 Pengurus
                        </Link>
                         <Link :href="route('pengurus_yayasan.index')" class="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600">
                            👥 Pengurus
                        </Link>
                         <Link :href="route('datayayasan.show', 1)" class="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600">
                            Lokasi Kantor
                        </Link>
                    </div>
                </div>
            </Transition>
        </div>

        <div class="relative group">
            <button 
                @click="isDropdownOpen = !isDropdownOpen"
                class="flex items-center space-x-1 text-gray-600 hover:text-blue-600 focus:outline-none"
                :class="{'text-blue-600 font-bold': route().current('video.*')}"
            >
                <span>Konten</span>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 transition-transform duration-200" :class="{'rotate-180': isDropdownOpen}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                </svg>
            </button>

            <!-- Dropdown Menu -->
            <Transition
                enter-active-class="transition ease-out duration-100"
                enter-from-class="transform opacity-0 scale-95"
                enter-to-class="transform opacity-100 scale-100"
                leave-active-class="transition ease-in duration-75"
                leave-from-class="transform opacity-100 scale-100"
                leave-to-class="transform opacity-0 scale-95"
            >
                <div v-if="isDropdownOpen" class="absolute left-0 mt-2 w-48 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 z-50">
                    <div class="py-1">
                        <Link :href="route('video.index')" class="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600">
                            📽️ Galeri Video
                        </Link>
                        <Link :href="route('fles.index')" class="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600">
                            📁 Arsip File
                        </Link>
                    </div>
                </div>
            </Transition>
        </div>

        <!-- KOTAK LOGIN INVISIBLE (Shortcut: Ctrl + Shift + Y) -->
        <Transition
            enter-active-class="transition ease-out duration-200"
            enter-from-class="opacity-0 scale-90"
            enter-to-class="opacity-100 scale-100"
            leave-active-class="transition ease-in duration-75"
            leave-from-class="opacity-100 scale-100"
            leave-to-class="opacity-0 scale-90"
        >
            <div v-if="isVisible" class="flex items-center">
                <Link 
                    :href="route('login')" 
                    class="bg-slate-800 text-white px-4 py-1.5 rounded-full shadow-xl text-xs font-bold tracking-wider border border-slate-700 hover:bg-red-600 transition-all duration-300 uppercase"
                >
                    🔒 Staff Access
                </Link>
            </div>
        </Transition>
    </nav>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue';
import { Link } from '@inertiajs/vue3';

// State untuk Hidden Login
const isVisible = ref(false);

// State untuk Dropdown
const isDropdownOpen = ref(false);
const dropdownRef = ref(null);

// Fungsi Shortcut Keyboard
const handleShortcut = (e) => {
    if (e.ctrlKey && e.shiftKey && e.key === 'Y') {
        e.preventDefault();
        isVisible.value = !isVisible.value;
    }
};

// Fungsi Klik Luar untuk menutup dropdown
const handleClickOutside = (event) => {
    if (dropdownRef.value && !dropdownRef.value.contains(event.target)) {
        isDropdownOpen.value = false;
    }
};

onMounted(() => {
    window.addEventListener('keydown', handleShortcut);
    window.addEventListener('click', handleClickOutside);
});

onUnmounted(() => {
    window.removeEventListener('keydown', handleShortcut);
    window.removeEventListener('click', handleClickOutside);
});
</script>

// resources/ts/Components/NavbarGuest.tsx
import { useState, useRef, useEffect } from 'react';

export default function NavbarGuest() {
  const [activeDropdown, setActiveDropdown] = useState<string | null>(null);
  const [isVisible, setIsVisible] = useState(false);
  const yayasanRef = useRef<HTMLDivElement>(null);
  const kontenRef = useRef<HTMLDivElement>(null);

  const toggleDropdown = (name: string) => {
    setActiveDropdown(activeDropdown === name ? null : name);
  };

  const handleClickOutside = (event: MouseEvent) => {
    if (
      yayasanRef.current &&
      !yayasanRef.current.contains(event.target as Node)
    ) {
      if (
        kontenRef.current &&
        !kontenRef.current.contains(event.target as Node)
      ) {
        setActiveDropdown(null);
      }
    }
  };

  const handleShortcut = (event: KeyboardEvent) => {
    if (event.ctrlKey && event.shiftKey && event.key === 'Y') {
      event.preventDefault();
      setIsVisible(!isVisible);
    }
  };

  useEffect(() => {
    window.addEventListener('click', handleClickOutside);
    window.addEventListener('keydown', handleShortcut);
    return () => {
      window.removeEventListener('click', handleClickOutside);
      window.removeEventListener('keydown', handleShortcut);
    };
  }, [isVisible, activeDropdown]);

  return (
    <nav className="flex items-center space-x-6">
      {/* Link Publik Biasa */}
      <a
        href="/"
        className="text-gray-600 hover:text-blue-600 transition-colors"
      >
        Beranda
      </a>

      {/* Menu Dropdown: Yayasan */}
      <div className="relative" ref={yayasanRef}>
        <button
          onClick={() => toggleDropdown('yayasan')}
          className={`flex items-center space-x-1 text-gray-600 hover:text-blue-600 focus:outline-none transition-colors ${
            activeDropdown === 'yayasan' ? 'text-blue-600 font-bold' : ''
          }`}
        >
          <span>Yayasan</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className={`h-4 w-4 transition-transform duration-200 ${
              activeDropdown === 'yayasan' ? 'rotate-180' : ''
            }`}
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M19 9l-7 7-7-7"
            />
          </svg>
        </button>

        {activeDropdown === 'yayasan' && (
          <div className="absolute left-0 mt-2 w-48 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 z-50">
            <div className="py-1">
              <a
                href="/posts/1"
                className="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-colors"
              >
                Visi
              </a>
              <a
                href="/posts/2"
                className="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-colors"
              >
                Misi
              </a>
              <a
                href="/posts/3"
                className="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-colors"
              >
                Sejarah
              </a>
              <a
                href="/pengurus"
                className="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-colors"
              >
                👥 Pengurus
              </a>
              <a
                href="/yayasan/lokasi"
                className="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-colors"
              >
                Lokasi Kantor
              </a>
            </div>
          </div>
        )}
      </div>

      {/* Menu Dropdown: Konten */}
      <div className="relative" ref={kontenRef}>
        <button
          onClick={() => toggleDropdown('konten')}
          className={`flex items-center space-x-1 text-gray-600 hover:text-blue-600 focus:outline-none transition-colors ${
            activeDropdown === 'konten' ? 'text-blue-600 font-bold' : ''
          }`}
        >
          <span>Konten</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className={`h-4 w-4 transition-transform duration-200 ${
              activeDropdown === 'konten' ? 'rotate-180' : ''
            }`}
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M19 9l-7 7-7-7"
            />
          </svg>
        </button>

        {activeDropdown === 'konten' && (
          <div className="absolute left-0 mt-2 w-48 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 z-50">
            <div className="py-1">
              <a
                href="/video"
                className="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 transition-colors"
              >
                📽️ Galeri Video
              </a>
              <a
                href="/files"
                className="block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 transition-colors"
              >
                📁 Arsip File
              </a>
            </div>
          </div>
        )}
      </div>

      {/* Tombol Login (Hidden) */}
      {isVisible && (
        <div className="flex items-center animate-in fade-in duration-200">
          <a
            href="/login"
            className="bg-slate-800 text-white px-4 py-1.5 rounded-full shadow-xl text-xs font-bold tracking-wider border border-slate-700 hover:bg-red-600 transition-all duration-300 uppercase"
          >
            🔒 Staff Access
          </a>
        </div>
      )}
    </nav>
  );
}
