// resources/ts/Pages/Video/Create.vue
<template>
    <div class="max-w-4xl mx-auto py-8">
        <!-- Header -->
        <div class="mb-6">
            <h2 class="text-2xl font-bold text-gray-800">Upload Video Baru</h2>
            <p class="text-sm text-gray-500 mt-1">Masukkan detail video YouTube yang ingin ditampilkan di website yayasan.</p>
        </div>

        <div class="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            <form @submit.prevent="submit" class="p-6 md:p-8">
                
                <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <!-- Kolom Kiri: Input Form Utama -->
                    <div class="space-y-6">
                        
                        <!-- Input: Judul -->
                        <div>
                            <label for="judul" class="block text-sm font-medium text-gray-700">Judul Video <span class="text-red-500">*</span></label>
                            <input 
                                type="text" 
                                id="judul" 
                                v-model="form.judul" 
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
                                placeholder="Masukkan judul video..."
                                required
                            >
                            <p v-if="form.errors.judul" class="mt-1 text-xs text-red-600">{{ form.errors.judul }}</p>
                        </div>

                        <!-- Input: Link YouTube -->
                        <div>
                            <label for="youtube_link" class="block text-sm font-medium text-gray-700">Link YouTube <span class="text-red-500">*</span></label>
                            <input 
                                type="text" 
                                id="youtube_link" 
                                v-model="rawYoutubeLink" 
                                @input="extractYoutubeId"
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
                                placeholder="https://www.youtube.com/watch?v=..."
                                required
                            >
                            <p class="mt-1 text-xs text-gray-500">Paste link YouTube. Sistem otomatis membaca ID-nya.</p>
                            <p v-if="form.errors.youtube_id" class="mt-1 text-xs text-red-600">{{ form.errors.youtube_id }}</p>
                        </div>

                        <!-- Input: Tanggal Upload -->
                        <div>
                            <label for="tanggal_upload" class="block text-sm font-medium text-gray-700">Tanggal Upload Video <span class="text-red-500">*</span></label>
                            <input 
                                type="date" 
                                id="tanggal_upload" 
                                v-model="form.tanggal_upload" 
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
                                required
                            >
                            <p class="mt-1 text-xs text-gray-500">Sesuaikan dengan tanggal rilis video di YouTube.</p>
                            <p v-if="form.errors.tanggal_upload" class="mt-1 text-xs text-red-600">{{ form.errors.tanggal_upload }}</p>
                        </div>

                        <!-- Input: Status Publikasi (Toggle On/Off) -->
                        <div>
                            <span class="block text-sm font-medium text-gray-700 mb-2">Status Publikasi</span>
                            <label class="flex items-center cursor-pointer">
                                <!-- Hidden Checkbox -->
                                <input type="checkbox" v-model="form.is_published" class="sr-only peer">
                                <!-- Toggle Background -->
                                <div class="relative w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                                <!-- Label Teks -->
                                <span class="ml-3 text-sm font-bold" :class="form.is_published ? 'text-blue-600' : 'text-gray-500'">
                                    {{ form.is_published ? 'ON (Tayang)' : 'OFF (Draft)' }}
                                </span>
                            </label>
                        </div>

                    </div>

                    <!-- Kolom Kanan: Preview Video -->
                    <div class="space-y-6">
                        
                        <!-- Auto-Preview Video -->
                        <div>
                            <label class="block text-sm font-medium text-gray-700 mb-1">Preview Video</label>
                            <div class="w-full aspect-video bg-gray-100 rounded-lg border-2 border-dashed border-gray-300 flex items-center justify-center overflow-hidden shadow-inner">
                                <iframe 
                                    v-if="form.youtube_id"
                                    class="w-full h-full"
                                    :src="`https://www.youtube.com/embed/${form.youtube_id}?rel=0`" 
                                    frameborder="0" 
                                    allowfullscreen
                                ></iframe>
                                <div v-else class="text-gray-400 text-sm flex flex-col items-center">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 mb-2 opacity-30" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
                                    </svg>
                                    Preview akan muncul setelah link dimasukkan
                                </div>
                            </div>
                        </div>

                        <!-- Input: Deskripsi Opsional -->
                        <div>
                            <label for="deskripsi" class="block text-sm font-medium text-gray-700">Deskripsi Singkat (Opsional)</label>
                            <textarea 
                                id="deskripsi" 
                                v-model="form.deskripsi" 
                                rows="3" 
                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
                                placeholder="Tambahkan keterangan singkat..."
                            ></textarea>
                            <p v-if="form.errors.deskripsi" class="mt-1 text-xs text-red-600">{{ form.errors.deskripsi }}</p>
                        </div>

                    </div>
                </div>

                <!-- Bagian Bawah: Tombol Aksi Create -->
                <div class="mt-8 pt-5 border-t border-gray-200 flex items-center justify-end space-x-3">
                    <Link 
                        :href="route('video.edit')" 
                        class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition"
                    >
                        Batal
                    </Link>
                    
                    <!-- Tombol Create -->
                    <button 
                        type="submit" 
                        :disabled="form.processing"
                        class="px-6 py-2 text-sm font-bold text-white bg-blue-600 border border-transparent rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center shadow-sm"
                    >
                        <svg v-if="form.processing" class="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                        <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
                        </svg>
                        {{ form.processing ? 'Menyimpan Data...' : 'Create Video' }}
                    </button>
                </div>
                
            </form>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useForm, Link } from '@inertiajs/vue3';

// Mengambil tanggal hari ini dalam format YYYY-MM-DD untuk default value
const today = new Date().toISOString().split('T')[0];

const form = useForm({
    judul: '',
    youtube_id: '',
    deskripsi: '',
    is_published: true, // Default tayang (ON)
    tanggal_upload: today, // Default otomatis hari ini
});

const rawYoutubeLink = ref('');

const extractYoutubeId = () => {
    const url = rawYoutubeLink.value;
    let videoId = '';

    const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
    const match = url.match(regExp);

    if (match && match[2].length === 11) {
        videoId = match[2];
    } else {
        if (url.length === 11) {
            videoId = url;
        }
    }

    form.youtube_id = videoId;
};

const submit = () => {
    if (!form.youtube_id) {
        alert("Link YouTube tidak valid. Harap masukkan link yang benar sebelum mempublikasikan.");
        return;
    }

    form.post(route('video.store'), {
        preserveScroll: true,
        onSuccess: () => {
            // Setelah berhasil, form dikosongkan dan dialihkan ke daftar video
            form.reset();
            rawYoutubeLink.value = '';
        },
    });
};
</script>

// resources/ts/Pages/Post/Create.tsx
import { Link, useForm } from '@inertiajs/react';
import { route } from 'ziggy-js';
import TextEditor from '@/Components/TextEditor';

interface PostFormData {
    title: string;
    body: string;
    published: boolean;
    published_at: string;
}

export default function Create() {
    const form = useForm<PostFormData>({
        title: '',
        body: '',
        published: false,
        published_at: new Date().toISOString().slice(0, 16),
    });

    const submit = () => {
        form.post(route('post.store'), {
            preserveScroll: true,
            onSuccess: () => form.reset(),
        });
    };

    return (
        <div className="max-w-5xl mx-auto py-10 px-4">
            <div className="mb-8">
                <Link
                    href={route('post.edit')}
                    className="text-sm text-blue-600 hover:underline flex items-center mb-2"
                >
                    Kembali ke Daftar Artikel
                </Link>
                <h1 className="text-3xl font-black text-gray-900 tracking-tight">
                    Tulis Artikel Baru
                </h1>
                <p className="text-sm text-gray-500 mt-1">
                    Lengkapi informasi artikel di bawah ini lalu publikasikan.
                </p>
            </div>

            <div className="bg-white rounded-3xl shadow-xl border border-gray-100 overflow-hidden">
                <form
                    onSubmit={(event) => {
                        event.preventDefault();
                        submit();
                    }}
                    className="p-8 md:p-12 space-y-8"
                >
                    <div>
                        <label className="block text-sm font-black text-gray-700 uppercase tracking-widest mb-2">
                            Judul Artikel
                        </label>
                        <input
                            type="text"
                            value={form.data.title}
                            onChange={(event) =>
                                form.setData('title', event.target.value)
                            }
                            className="w-full px-5 py-4 bg-gray-50 border-transparent rounded-2xl focus:bg-white focus:ring-4 focus:ring-blue-100 focus:border-blue-500 transition-all text-xl font-bold"
                            placeholder="Masukkan judul artikel..."
                        />
                        {form.errors.title && (
                            <div className="text-red-500 text-xs mt-2 font-bold">
                                {form.errors.title}
                            </div>
                        )}
                    </div>

                    <div>
                        <label className="block text-sm font-black text-gray-700 uppercase tracking-widest mb-2">
                            Isi Artikel
                        </label>
                        <TextEditor
                            value={form.data.body}
                            onChange={(html) => form.setData('body', html)}
                        />
                        {form.errors.body && (
                            <div className="text-red-500 text-xs mt-2 font-bold">
                                {form.errors.body}
                            </div>
                        )}
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-6 border-t border-gray-50">
                        <div>
                            <label className="block text-sm font-black text-gray-700 uppercase tracking-widest mb-4">
                                Status Publikasi
                            </label>
                            <div className="flex items-center space-x-4">
                                <button
                                    type="button"
                                    onClick={() =>
                                        form.setData(
                                            'published',
                                            !form.data.published,
                                        )
                                    }
                                    className={`relative inline-flex h-8 w-14 items-center rounded-full transition-colors focus:outline-none ${
                                        form.data.published
                                            ? 'bg-green-500'
                                            : 'bg-gray-300'
                                    }`}
                                >
                                    <span
                                        className={`inline-block h-6 w-6 transform rounded-full bg-white transition-transform shadow-md ${
                                            form.data.published
                                                ? 'translate-x-7'
                                                : 'translate-x-1'
                                        }`}
                                    />
                                </button>
                                <span
                                    className={`font-bold text-sm ${
                                        form.data.published
                                            ? 'text-green-600'
                                            : 'text-gray-400'
                                    }`}
                                >
                                    {form.data.published
                                        ? 'PUBLISHED (Aktif)'
                                        : 'DRAFT (Tersembunyi)'}
                                </span>
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-black text-gray-700 uppercase tracking-widest mb-2">
                                Tanggal Terbit
                            </label>
                            <input
                                type="datetime-local"
                                value={form.data.published_at}
                                onChange={(event) =>
                                    form.setData(
                                        'published_at',
                                        event.target.value,
                                    )
                                }
                                className="w-full px-4 py-3 bg-gray-50 border-transparent rounded-xl focus:bg-white focus:ring-4 focus:ring-blue-100 focus:border-blue-500 transition-all font-bold"
                            />
                            {form.errors.published_at && (
                                <div className="text-red-500 text-xs mt-2 font-bold">
                                    {form.errors.published_at}
                                </div>
                            )}
                        </div>
                    </div>

                    <div className="pt-10 flex flex-col md:flex-row items-center justify-between gap-4">
                        <Link
                            href={route('post.edit')}
                            className="px-8 py-4 text-gray-400 font-bold hover:text-gray-600 transition-colors"
                        >
                            Batal
                        </Link>

                        <button
                            type="submit"
                            disabled={form.processing}
                            className="w-full md:w-auto px-10 py-4 bg-gray-900 text-white rounded-2xl font-black shadow-xl shadow-gray-200 hover:bg-blue-600 transition-all active:scale-95 disabled:opacity-50 flex items-center justify-center"
                        >
                            {form.processing ? 'Menyimpan...' : 'Publikasikan Artikel'}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
}
